### ISSUE TITLE
Not loading the presets

### ISSUE THREAD

**Issue by emman-m** [sirosss/mg30-controller#1]
every time i connect with mg30 this error always pop and cancel the whole operation. 
this is my preset value `effectTypeChain: [5, 0, 1, 2, 3, 9, 4, 10, 7, 6, 8, 11]`
```
[log] Error during processing MIDI message
      Exception: Unrecognized GATE preset data
      #0      DeviceModel._getDualCodeTypeBlock (package:mg30controller/models/device.dart:394:5)
      #1      DeviceModel._populateEffectChain (package:mg30controller/models/device.dart:311:27)
      #2      DeviceModel._loadAllDeviceData (package:mg30controller/models/device.dart:178:13)
      #3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
      #4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
      #5      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
      #6      _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
      #7      _MapStream._handleData (dart:async/stream_pipe.dart:218:10)
      #8      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
      #9      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
      #10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
      #11     _DelayedData.perform (dart:async/stream_impl.dart:515:14)
      #12     _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
      #13     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
      #14     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
      #15     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
```

**Comment by sirosss** [comment]
The error message implies an unknown binary code in the position of gate effect block in the preset data.
When the app connects to MG-30, it loads the effect chain from the current preset. That preset seems to be causing the problem.

Would you mind exporting the preset on QuickTone and sending the export file to me? I will check why it is not recognized and how it is shown in MG-30.

Thank you very much.

**Comment by emman-m** [comment]
Here is the preset. @sirosss 
[preset.zip](https://github.com/sirosss/mg30-controller/files/13464391/preset.zip)

**Comment by sirosss** [comment]
I loaded your preset into my MG-30, and when I use the app to read the preset, I got an error about an unrecognized wah type.
I looked into the data, and it is indeed an unknown value for a wah type.

I checked the preset on MG-30 and QuickTone, and there is something strange about it.
Comparing to factory preset 2D, here is what I see on QuickTone.

![2D PeteT Rotorgrind - Wah Block](https://github.com/sirosss/mg30-controller/assets/14882937/4eadfed1-62fc-4bfb-8574-4e90204bd24e)

When right click on the wah block, it shows the dropdown selection, highlighting the selected Horse Wah.
And below is your preset. Notice that there is no highlight in the selection dropdown. And the image for the Wah is broken.

![VOX30 CLEAN - Wah Block](https://github.com/sirosss/mg30-controller/assets/14882937/15ac5c51-2cd2-4d25-82ad-697eecf1a089)

Also when go to the EXP & Pedal settings from the top bar, normally if expression pedal (no. 1) is set to controlled the wah, it will show the selected wah type as shown below.

![2D PeteT Rotorgrind - EXP](https://github.com/sirosss/mg30-controller/assets/14882937/753ace4c-b882-4296-a2ab-88034198e658)

Your preset does not show a wah type, and it shows "EQ" in the third block.

![VOX30 CLEAN - EXP](https://github.com/sirosss/mg30-controller/assets/14882937/3a4e69a7-ef60-4137-8445-67f8b35dba82)

I saved your preset into another preset slot, changed the wah type to something else, and it now can be read the app.
It still has an issue with EXP control though.

I don't think it is possible to create something like this on MG-30 or QuickTone, at least on the latest version of the firmware.
It seems MG-30 and QuickTone are tolerant of unknown effect type and just default to the first effect in the category.
I'm not sure if the app should do the same. It could potentially create more issues down the line, and it will be very difficult to trace back to this root cause.

How did you make this preset? And are you on the latest firmware version?
If this is created on the latest firmware version, we should report it as a bug to NUX.

**Comment by emman-m** [comment]
Thanks for the info's, I think I've created this preset on past version of firmware and import it into 4.0.3. I will try to re create this preset. I'll get back to you as soon.

**Comment by emman-m** [comment]
Hi @sirosss I find out that if I'm going to edit my preset on mg30, it will not continue to load the preset thru this app.

**Comment by sirosss** [comment]
Are we still talking about the preset you sent earlier in this thread or is this just any presets in general?

Also please attach the preset that you have the issue with and describe the steps to reproduce the issue.

**Comment by sirosss** [comment]
Closed due to insufficient info on the issue.
